version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    groups:
      routine-nuget-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    groups:
      routine-action-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    groups:
      routine-container-updates:
        update-types:
          - minor
          - patch
