name: .NET Core Master and Deploy Checks

on: 
  push:
    branches: 
      - master
      - deploy
  pull_request:
    branches: 
      - master
      - deploy
  release:
    types: 
      -created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
